version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd generate_data
      - zip -r deployment_package_ecommerce.zip *.py
  post_build:
    commands:
      - echo "Uploading to S3..."
      - aws s3 cp deployment_package_ecommerce.zip s3://lambda-builds-zip-yb/
      - echo "Updating Lambda function via S3..."
      - aws lambda update-function-code --function-name ecommerce-generate-data --s3-bucket lambda-builds-zip-yb --s3-key deployment_package_ecommerce.zip
      - echo "Deployment complete!"
      - cd ..